// One-time migration: extract the <main class="article"> body from each legacy
// blog article in docs/blog/*.html and emit src/data/article-bodies.ts so the
// new Astro blog/article page can render the same prose inside the site chrome.
//
// Also rewires links to the retired /brand-strategy.html page to the homepage
// About section (/about), which covers the same ground.
//
// Run:  node scripts/migrate_blog.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DOCS_BLOG = join(process.cwd(), "docs", "blog");
const OUT_FILE = join(process.cwd(), "src", "data", "article-bodies.ts");

const slugs = readdirSync(DOCS_BLOG)
  .filter((name) => name.endsWith(".html") && name !== "index.html")
  .map((name) => name.replace(/\.html$/, ""))
  .sort();

const bodies = {};
for (const slug of slugs) {
  let html = readFileSync(join(DOCS_BLOG, `${slug}.html`), "utf8");
  let body;
  const mainMatch = html.match(/<main class="article">([\s\S]*?)<\/main>/);
  if (mainMatch) {
    body = mainMatch[1].trim();
  } else {
    const articleMatch = html.match(/<article[^>]*>([\s\S]*?)<\/article>/);
    if (articleMatch) {
      body = articleMatch[1].trim();
    }
  }
  if (!body) {
    console.warn(`SKIP ${slug}: no article body block found`);
    continue;
  }
  // The Astro layout supplies its own header, so drop a legacy hero header
  // when an article carries one inside its body (e.g. the personal-story post).
  body = body.replace(/^\s*<header class="hero[\s\S]*?<\/header>\s*/, "").trim();
  // Stop at an article end-navigation block if the legacy page had one.
  body = body.replace(/\s*<nav class="story-navigation"[\s\S]*$/, "").trim();
  // The legacy /brand-strategy.html page is being retired. Its role is now
  // covered by the homepage About section.
  body = body.replaceAll('href="/brand-strategy.html"', 'href="/#about"');
  bodies[slug] = body;
}

const source =
  "// Generated by scripts/migrate_blog.mjs - do not edit by hand.\n" +
  "// Keyed by article slug (see src/data/articles.ts). HTML bodies rendered\n" +
  "// with set:html inside the blog article layout.\n" +
  "export const ARTICLE_BODIES: Record<string, string> = " +
  JSON.stringify(bodies, null, 2) +
  ";\n";

writeFileSync(OUT_FILE, source);
console.log(`Wrote ${Object.keys(bodies).length} article bodies to src/data/article-bodies.ts`);